=== roehlsystem/My-pama-test-scripts/Expev/CFG_Mapping.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Irene Filipponi (Hewlett Packard) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="CFG_XML_Map">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Element_Map" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="PVAR_UNITS" maxOccurs="unbounded">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute name="PVAR_ID" type="xs:unsignedInt" use="required"/>
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="PRODUCT_KEY" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string"/>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="COMPONENT_CLASS" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="HOST_ASSEMBLY"/>
									<xs:enumeration value="NOT VALID"/>
									<xs:enumeration value="ON-PRIMARY MATERIAL"/>
									<xs:enumeration value="ON-RETAIL PKG MATERIAL"/>
									<xs:enumeration value="PEN/INK"/>
									<xs:enumeration value="PRIMARY ASSEMBLY (BULK)"/>
									<xs:enumeration value="PRIMARY PACKAGING"/>
									<xs:enumeration value="RECEPTACLE LABEL"/>
									<xs:enumeration value="RETAIL BUNDLE"/>
									<xs:enumeration value="RETAIL MASTERSHIP"/>
									<xs:enumeration value="RETAIL PACKAGING"/>
									<xs:enumeration value="WET ASSEMBLY"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" type="xs:decimal" use="optional" default="0.93"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== roehlsystem/My-pama-test-scripts/Expev/Pama_CFG_Mapping.xml
<?xml version="1.0" encoding="UTF-8"?><!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Irene Filipponi (Hewlett Packard) --><!--Sample XML file generated by XMLSPY v2004 rel. 3 U (http://www.xmlspy.com)--><CFG_XML_Map xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="CFG_Mapping.xsd" version="0.93">	<Element_Map PRODUCT_KEY="SmartDate" COMPONENT_CLASS="PRIMARY PACKAGING">		<PVAR_UNITS PVAR_ID="0">PART_PREFIX</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Markem Bulk" COMPONENT_CLASS="HOST_ASSEMBLY">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the PRINTER LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Labelaire" COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the PRINTER LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Lot+" COMPONENT_CLASS="RETAIL MASTERSHIP">		<PVAR_UNITS PVAR_ID="0"/>		<PVAR_UNITS PVAR_ID="1"/>		<PVAR_UNITS PVAR_ID="2"/>		<PVAR_UNITS PVAR_ID="3"/>		<PVAR_UNITS PVAR_ID="4"/>		<PVAR_UNITS PVAR_ID="5"/>		<PVAR_UNITS PVAR_ID="6"/>		<PVAR_UNITS PVAR_ID="7"/>	</Element_Map>	<Element_Map PRODUCT_KEY="Markem PCC" COMPONENT_CLASS="RETAIL PACKAGING">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the PRINTER LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Checkweigher" COMPONENT_CLASS="RETAIL PACKAGING">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the SCALE LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Marsh" COMPONENT_CLASS="RETAIL MASTERSHIP">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the PRINTER LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Trcablty PCC" COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">		<PVAR_UNITS PVAR_ID="0">			<!--Left Blank because templates will be stored in scripts, and the transfered values will only have templates.  In the future this needs to be just PICA-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Markem Int" COMPONENT_CLASS="RETAIL PACKAGING">		<PVAR_UNITS PVAR_ID="0">			<!-- Left Blank because the PRINTER LEGENDs will need to be standardized.-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Pen Body" COMPONENT_CLASS="PEN/INK">		<PVAR_UNITS PVAR_ID="0">MINA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Pouch" COMPONENT_CLASS="PRIMARY PACKAGING">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Sleeve" COMPONENT_CLASS="PRIMARY PACKAGING">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Pouch2" COMPONENT_CLASS="PRIMARY PACKAGING">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Sleeve2" COMPONENT_CLASS="PRIMARY PACKAGING">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Trcablty Bulk" COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">		<PVAR_UNITS PVAR_ID="0">			<!--Left Blank because templates will be stored in scripts, and the transfered values will only have templates (Traceability,ProcessDate, Lot#, and/or Productnumber).  In the future this needs to be just PICA and possibly Selectability Number-->		</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">			<!--Left Blank because templates will be stored in scripts, and the transfered values will only have templates (Traceability,ProcessDate, Lot#, and/or Productnumber).  In the future this needs to be just PICA and possibly Selectability Number-->		</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">			<!--Left Blank because templates will be stored in scripts, and the transfered values will only have templates (Traceability,ProcessDate, Lot#, and/or Productnumber).  In the future this needs to be just PICA and possibly Selectability Number-->		</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">			<!--Left Blank because templates will be stored in scripts, and the transfered values will only have templates (Traceability,ProcessDate, Lot#, and/or Productnumber).  In the future this needs to be just PICA and possibly Selectability Number-->		</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Traceblty Label Print" COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">QTY</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Leaflet" COMPONENT_CLASS="ON-PRIMARY MATERIAL">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="1-Up" COMPONENT_CLASS="RETAIL PACKAGING">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">PICA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="UPC Symbol" COMPONENT_CLASS="RETAIL PACKAGING">		<PVAR_UNITS PVAR_ID="0">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="2">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="3">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="4">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="5">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="6">UPC</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="7">UPC</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="WARP 9 ID" COMPONENT_CLASS="PEN/INK">		<PVAR_UNITS PVAR_ID="0">MINA</PVAR_UNITS>	</Element_Map>	<Element_Map PRODUCT_KEY="Mastership" COMPONENT_CLASS="RETAIL MASTERSHIP">		<PVAR_UNITS PVAR_ID="0"/>		<PVAR_UNITS PVAR_ID="1"/>		<PVAR_UNITS PVAR_ID="2"/>		<PVAR_UNITS PVAR_ID="3"/>		<PVAR_UNITS PVAR_ID="4"/>		<PVAR_UNITS PVAR_ID="5"/>		<PVAR_UNITS PVAR_ID="6"/>		<PVAR_UNITS PVAR_ID="7"/>	</Element_Map>	<Element_Map PRODUCT_KEY="Default" COMPONENT_CLASS="NOT VALID">		<PVAR_UNITS PVAR_ID="0"/>		<PVAR_UNITS PVAR_ID="1"/>		<PVAR_UNITS PVAR_ID="2"/>	</Element_Map>	<Element_Map PRODUCT_KEY="Zebra" COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">		<PVAR_UNITS PVAR_ID="0">PICA</PVAR_UNITS>		<PVAR_UNITS PVAR_ID="1">QTY</PVAR_UNITS>	</Element_Map></CFG_XML_Map>
