=== roehlsystem/My-pama-test-scripts/Expev/PamaCFG.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 3 U (http://www.xmlspy.com) by Irene Filipponi (private) -->
<!--W3C Schema generated by XMLSPY v5 rel. 4 U (http://www.xmlspy.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="PRODUCT_RECIPE">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="ASSEMBLY_NUMBER">
					<xs:annotation>
						<xs:documentation>Typically for PCCs this is a Product Number, for the factories this is a Part Assembly number</xs:documentation>
					</xs:annotation>
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="(\d{5}[A-Z]{2}-\d{3}|\d{5}-\d{5}|\d{4}-\d{4})"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="INSTALLBY_DATE_OFFSET" type="xs:nonNegativeInteger" default="18">
					<xs:annotation>
						<xs:documentation>This is the number of months from the current date that this product should be install by.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="EXPIRATION_DATE_OFFSET" type="xs:nonNegativeInteger" default="24" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This is the number of months from the current date the the product should be expended by</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="FILE_CREATED_DATE" type="xs:dateTime" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This is the date that this CFG file was created.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="LAST_RUN_DATE" type="xs:dateTime" minOccurs="0">
					<xs:annotation>
						<xs:documentation>This is the date that this CFG file was last used.</xs:documentation>
					</xs:annotation>
				</xs:element>
				<xs:element name="COMPONENT" maxOccurs="unbounded">
					<xs:annotation>
						<xs:documentation>Contains a required COMPONENT_CLASS attribute that must be one of the following examples: Pen/Ink Receptacle Label,Retail Mastership,Primary Packaging,Primary Assembly (Bulk),Wet Assembly,On-Primary Material,Retail Packaging,Retail Bundle,On-Retail Pkg Material,Host Assembly.  It also has an Optional (but required for automation) attribute PART_REF This attribute contains either the part number (4x4 or 5x5, if it has one), or the Assembly number (7x3).</xs:documentation>
					</xs:annotation>
					<xs:complexType>
						<xs:sequence>
							<xs:element name="LAST_UPDATED" type="xs:dateTime">
								<xs:annotation>
									<xs:documentation>This is the Last date that this  device data was updated.</xs:documentation>
								</xs:annotation>
							</xs:element>
							<xs:element name="DATA_SOURCE">
								<xs:annotation>
									<xs:documentation>PVAR data may be updated from external systems.  These tags are used by those systems to determine how to update the data associated with this Device Type.  The Currently_Selected attribute designates the current method for updating data </xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="STATIC" minOccurs="0">
											<xs:annotation>
												<xs:documentation>Do not update this Data.  This is the default condition</xs:documentation>
											</xs:annotation>
											<xs:complexType/>
										</xs:element>
										<xs:element name="REMOTELY_MANAGED" minOccurs="0">
											<xs:annotation>
												<xs:documentation>This tag contains configuration data for the Symposium Client.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CONFIGURATION" type="xs:string"/>
												</xs:sequence>
												<xs:attribute name="FailureCount" type="xs:nonNegativeInteger" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="LOCALLY_MANAGED" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="DB_TABLENAME" type="xs:string"/>
													<xs:element name="DB_DATA_COLUMN_NAME" type="xs:string"/>
													<xs:element name="DB_WHERE_STATEMENT" type="xs:string"/>
													<xs:element name="DB_ORDERBY_STATEMENT" type="xs:string" minOccurs="0"/>
												</xs:sequence>
												<xs:attribute name="FailureCount" type="xs:nonNegativeInteger" use="required"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="ADO" minOccurs="0">
											<xs:annotation>
												<xs:documentation>This Update method may result in a Recordset, who's first column will be used to create PVAR_DATA/DATA.  It may also be used to UPDATE or INSERT records.</xs:documentation>
											</xs:annotation>
											<xs:complexType>
												<xs:sequence>
													<xs:element name="CONNECTION_STRING" type="xs:string">
														<xs:annotation>
															<xs:documentation>This is the ADO connection string for connecting to</xs:documentation>
														</xs:annotation>
													</xs:element>
													<xs:element name="COMMAND_STRING" type="xs:string">
														<xs:annotation>
															<xs:documentation>This is a SQL command.  If it returns a Record set, it will be used to fill in data in PVAR_DATA</xs:documentation>
														</xs:annotation>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="FailureCount" type="xs:nonNegativeInteger" use="required"/>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="Currently_Selected" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="STATIC"/>
												<xs:enumeration value="REMOTELY_MANAGED"/>
												<xs:enumeration value="LOCALLY_MANAGED"/>
												<xs:enumeration value="ADO"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
							<xs:element name="ATTRIBUTES" maxOccurs="unbounded">
								<xs:annotation>
									<xs:documentation>The SEQUENCE_NUMBER Attribute assigns the order of this Tag.  It relates directly to the Pama PVAR number sequence.</xs:documentation>
								</xs:annotation>
								<xs:complexType>
									<xs:sequence>
										<xs:element name="CREATION_DATE" type="xs:dateTime">
											<xs:annotation>
												<xs:documentation>This is the date that the Data was initially released to the world for use.</xs:documentation>
											</xs:annotation>
										</xs:element>
										<xs:element name="DATA" type="xs:string">
											<xs:annotation>
												<xs:documentation>This is the useable information</xs:documentation>
											</xs:annotation>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="SEQUENCE_NUMBER" type="xs:nonNegativeInteger" use="required"/>
									<xs:attribute name="UNITS" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value=""/>
												<xs:enumeration value="BOM ITEM">
													<xs:annotation>
														<xs:documentation>This contains the BOM items that should be present under this component class.</xs:documentation>
													</xs:annotation>
												</xs:enumeration>
												<xs:enumeration value="CM"/>
												<xs:enumeration value="FL OZ"/>
												<xs:enumeration value="GRAMS"/>
												<xs:enumeration value="INCHES"/>
												<xs:enumeration value="INK CHEMISTRY"/>
												<xs:enumeration value="INK COLOR"/>
												<xs:enumeration value="ITF-14"/>
												<xs:enumeration value="MID/PID"/>
												<xs:enumeration value="MINA"/>
												<xs:enumeration value="ML"/>
												<xs:enumeration value="OZ"/>
												<xs:enumeration value="PART NUMBER"/>
												<xs:enumeration value="PART PREFIX"/>
												<xs:enumeration value="PCC OPTION CODE"/>
												<xs:enumeration value="PICA"/>
												<xs:enumeration value="PRODUCT NUMBER"/>
												<xs:enumeration value="QTY"/>
												<xs:enumeration value="SELECTABILITY"/>
												<xs:enumeration value="UPC"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="COMPONENT_CLASS" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="HOST_ASSEMBLY"/>
									<xs:enumeration value="NOT VALID"/>
									<xs:enumeration value="ON-PRIMARY MATERIAL"/>
									<xs:enumeration value="ON-RETAIL PKG MATERIAL"/>
									<xs:enumeration value="PEN/INK"/>
									<xs:enumeration value="PRIMARY ASSEMBLY (BULK)"/>
									<xs:enumeration value="PRIMARY PACKAGING"/>
									<xs:enumeration value="RECEPTACLE LABEL"/>
									<xs:enumeration value="RETAIL BUNDLE"/>
									<xs:enumeration value="RETAIL MASTERSHIP"/>
									<xs:enumeration value="RETAIL PACKAGING"/>
									<xs:enumeration value="WET ASSEMBLY"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
						<xs:attribute name="PART_REF" use="optional">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="(\d{5}[A-Z]{2}-\d{3}|\d{5}-\d{5}|\d{4}-\d{4})"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="version" use="optional" default="0.94">
				<xs:simpleType>
					<xs:restriction base="xs:decimal">
						<xs:pattern value="\d{1,2}.\d{1,3}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== roehlsystem/My-pama-test-scripts/Expev/PamaCfg.xml
<?xml version="1.0" encoding="UTF-8"?>
<PRODUCT_RECIPE version="1.000000" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="http://suppliespackaging.hp.com/XMLschema/PamaCFG.xsd">
<ASSEMBLY_NUMBER>3YP03BL</ASSEMBLY_NUMBER>
<INSTALLBY_DATE_OFFSET>18</INSTALLBY_DATE_OFFSET>
<FILE_CREATED_DATE>2006-01-09T09:15:37Z</FILE_CREATED_DATE>
<COMPONENT COMPONENT_CLASS="NOT VALID">
<LAST_UPDATED>2006-01-09T09:15:37Z</LAST_UPDATED>
<DATA_SOURCE Currently_Selected="STATIC">
<STATIC></STATIC>
<REMOTELY_MANAGED FailureCount="0">
<CONFIGURATION></CONFIGURATION>
</REMOTELY_MANAGED>
<LOCALLY_MANAGED FailureCount="0">
<DB_TABLENAME></DB_TABLENAME>
<DB_DATA_COLUMN_NAME></DB_DATA_COLUMN_NAME>
<DB_WHERE_STATEMENT></DB_WHERE_STATEMENT>
</LOCALLY_MANAGED>
<ADO FailureCount="0">
<CONNECTION_STRING></CONNECTION_STRING>
<COMMAND_STRING></COMMAND_STRING>
</ADO>
</DATA_SOURCE>
<ATTRIBUTES SEQUENCE_NUMBER="0" UNITS="PICA POUCH">
<CREATION_DATE>2006-01-09T09:15:37Z</CREATION_DATE>
<DATA></DATA>
</ATTRIBUTES>
<ATTRIBUTES SEQUENCE_NUMBER="1" UNITS="WO REQUIRED">
<CREATION_DATE>2006-01-09T09:15:37Z</CREATION_DATE>
<DATA>NOT REQUIRED</DATA>
</ATTRIBUTES>
<ATTRIBUTES SEQUENCE_NUMBER="2" UNITS="WORK ORDER">
<CREATION_DATE>2006-01-09T09:15:37Z</CREATION_DATE>
<DATA>001000522322</DATA>
</ATTRIBUTES>
</COMPONENT>
</PRODUCT_RECIPE>

=== roehlsystem/My-pama-test-scripts/Expev/cfg/default.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?><PRODUCT_RECIPE version="1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://suppliespackaging.hp.com/XMLschema/PamaCFG.xsd">
<ASSEMBLY_NUMBER>XXXXXX-XXX</ASSEMBLY_NUMBER>
<INSTALLBY_DATE_OFFSET>18</INSTALLBY_DATE_OFFSET>
<FILE_CREATED_DATE>2004-09-21T05:03:25Z</FILE_CREATED_DATE>
<COMPONENT COMPONENT_CLASS="PRIMARY ASSEMBLY (BULK)">
<LAST_UPDATED>2005-06-12T19:13:44Z</LAST_UPDATED>
<DATA_SOURCE Currently_Selected="STATIC"/>
<ATTRIBUTES SEQUENCE_NUMBER="0" UNITS="PICA">
<CREATION_DATE>2005-06-12T19:13:44Z</CREATION_DATE>
<DATA>HP</DATA>
</ATTRIBUTES>
</COMPONENT>
</PRODUCT_RECIPE>
